---
# Install Trusted Software Factory using tssc-cli

# Deploy TSF with integrations
- name: Deploy TSF and integrations
  ansible.builtin.include_tasks: deploy_tsf.yml

# Configure Keycloak and OpenShift authentication
- name: Configure Keycloak authentication
  ansible.builtin.include_tasks: configure_authentication.yml

# Save TSF access information
- name: Get Keycloak route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: keycloak
    namespace: "{{ ocp4_workload_trusted_software_factory_keycloak_namespace }}"
  register: r_keycloak_route

- name: Save TSF access information to user data
  agnosticd.core.agnosticd_user_info:
    data:
      openshift_console_url: "https://console-openshift-console.{{ openshift_cluster_ingress_domain }}"
      openshift_admin_username: "{{ ocp4_workload_trusted_software_factory_keycloak_admin_username }}"
      openshift_admin_password: "{{ ocp4_workload_trusted_software_factory_keycloak_admin_password }}"
      tsf_keycloak_url: "https://{{ r_keycloak_route.resources[0].spec.host }}"
      tsf_keycloak_admin_username: "{{ ocp4_workload_trusted_software_factory_keycloak_admin_username }}"
      tsf_keycloak_admin_password: "{{ ocp4_workload_trusted_software_factory_keycloak_admin_password }}"
      tsf_namespace: "{{ ocp4_workload_trusted_software_factory_namespace }}"
      tsf_tas_namespace: "{{ ocp4_workload_trusted_software_factory_tas_namespace }}"
      tsf_tpa_namespace: "{{ ocp4_workload_trusted_software_factory_tpa_namespace }}"
      tsf_konflux_namespace: "{{ ocp4_workload_trusted_software_factory_konflux_namespace }}"

# Cleanup
- name: Delete TSSC CLI pod
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Pod
    name: tssc-cli
    namespace: "{{ ocp4_workload_trusted_software_factory_namespace }}"
