---
- name: Install Orchestrator Operator
  block:
  - name: Install Orchestrator Operator
    ansible.builtin.include_role:
      name: install_operator
    vars:
      install_operator_action: install
      install_operator_name: kubernetes-imagepuller-operator
      install_operator_namespace: openshift-operators
      install_operator_channel: "{{ ocp4_workload_kubernetes_image_puller_operator_channel }}"
      install_operator_catalog: community-operators
      install_operator_packagemanifest_name: kubernetes-imagepuller-operator
      install_operator_automatic_install_plan_approval: true
      install_operator_csv_nameprefix: kubernetes-imagepuller-operator

- name: Install KIP instance
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_kubernetes_image_puller_instance_namespace }}"
    definition: "{{ lookup('template', 'kubernetes_image_puller_instance.yml.j2') | from_yaml }}"

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool
